version: "3.8"

services:
        ideliumfe:
                image:
                        ifuschini/ideliumfe
                ports:
                        - 443:443
                links:
                        - 'ideliumdb'
                networks:
                        - idelium_net
                environment:
                        dbhost: "ideliumdb"
                        be: "ideliumapi"

        ideliumapi:
                image:
                        ifuschini/ideliumapi
                links:
                        - 'ideliumdb'
                networks:
                        - idelium_net
                environment:
                        dbhost: "ideliumdb"
                depends_on:
                        ideliumdb:
                                condition: service_healthy
        ideliumdb:
                image:
                        ifuschini/ideliumdb
                networks:
                        - idelium_net
                environment:
                        MYSQL_USER: ideliumadmin
                        MYSQL_PASSWORD: idelium                        
                healthcheck:
                        test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
                        start_period: 5s
                        interval: 5s
                        timeout: 5s
                        retries: 55
networks:
  idelium_net:
    driver: bridge
